### ISSUE TITLE
Enhancement: Highlighting the parameter in request tab

### ISSUE THREAD

**Issue by madaratech** [bugcrowd/HUNT#11]
Thanks for making it, 

while using it i noticed once Hunt list some suspected parameter, after selecting the suspected request, we directly don't notice the suspected parameter in the request, so it can be helpful to highlight the suspected parameter in request tab specifically in cases where multiple params getting sent.

**Comment by swagnetow** [comment]
@madaratech Thanks for the kind words. The way HUNT is handling it right now is that each potentially vuln parameter is its own entry in the table; even if there are multiple parameters being sent that match the regex. I'm currently adding a separate column to that table that tells you the exact parameter that was found. I'm also working on using the request/response viewer API, however it does not expose a way to automatically highlight the potentially vuln parameter. Currently, only the the text editor API allows for that highlighting.

**Comment by madaratech** [comment]
Hey @swagnetow i'm not much familiar with burp extension dev but glad to know you are working on something related to this.

Cheers!
