### ISSUE TITLE
Kali Linux Install

### ISSUE THREAD

**Issue by carms642** [bugcrowd/HUNT#12]
How exactly this plugin is installed?
OS=Kali
Burp Pro:1.7.20
![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/11415252/29496184-47dd4668-85d6-11e7-9040-b96f0a4a6a19.png)
jython was installed.
What am I doing wrong.

**Comment by swagnetow** [comment]
@carms642 Did you set up Burp Suite to call the Jython standalone JAR in the `Options` tab? I will add installation instructions to the `README.md`.

**Comment by l50** [comment]
@carms642 Give this a shot:

0. Clone into the hunt repo
1. Download the jython standalone jar from here: http://www.jython.org/downloads.html
2. Open Burp Suite
3. Click Extender
4. Click Options
5. Under Python Environment, click Select file, and find the jar you downloaded in step 1. When you find it, double click it.
6. Click Extensions
7. Click Add
8. Click Select file ...
9. Find hunt_methodology (wherever it is on your system)
10. Double click it
11. Click Next; once it's done loading, click Close.
12. Starting at Step 7, do the same thing for the hunt scanner
