### ISSUE TITLE
No Information loaded 

### ISSUE THREAD

**Issue by d1pakda5** [bugcrowd/HUNT#14]
check the screenshot : http://prntscr.com/gj6lhe

**Comment by aoprea1982** [comment]
In my opinion the Resources and Notes Tab should be manually edited. 

![burp26](https://user-images.githubusercontent.com/16059481/30371996-53205d6e-98b7-11e7-947e-f481f8a12d63.jpg)

![burp24](https://user-images.githubusercontent.com/16059481/30372027-77c1abe6-98b7-11e7-9b13-4fb54cfc0663.jpg)

![burp25](https://user-images.githubusercontent.com/16059481/30372034-7bd1e066-98b7-11e7-80e2-8073391286a8.jpg)



Would the authors confirm it  or correct me?

**Comment by swagnetow** [comment]
Are you still running into this issue with the newest version of HUNT?
