### ISSUE TITLE
Possible count issue with the potential targets

### ISSUE THREAD

**Issue by ProDigySML** [bugcrowd/HUNT#29]
There seem to be more number of findings shown in the brackets than there is within the table, as displayed below:
![image](https://user-images.githubusercontent.com/16996819/32816967-808720ec-ca0f-11e7-8367-9d15da6807e9.png)
Not 100% sure if I am missing something. Might be that some records can actually have multiple numbers.

Also, as you can see within the image, it is possible to get negative findings too :)

**Comment by swagnetow** [comment]
@ProDigySML Thanks for reporting the issue. This is definitely a known issue on our side. We're working on a fix as this is a pretty big bug.

**Comment by swagnetow** [comment]
@ProDigySML Also, do you know of a way to get the bug to reproduce? I'm trying to fix it, but I'm having trouble getting the bug trigger again.

**Comment by ProDigySML** [comment]
I usually just click on the checked area to make it true, then use my keyboard to keep that column selected (the little blue box should be on the checked column for any row with true). Then hit the esc button and then the right arrow key. This should decrease the count to -1. Hope that helps!

**Comment by swagnetow** [comment]
@ProDigySML I was able to reproduce the bug, but unfortunately, I can't really fix that other than disabling certain key presses in your specific case. I did however fix the overall issue of HUNT reporting the wrong number of issues.

I'm going to close out this issue, but I highly appreciate the bug report as it lead me to fix a different bug that was a larger issue. Thanks!
