### ISSUE TITLE
Automatic search in request and response of HUNT Scanner (Nice to have feature)

### ISSUE THREAD

**Issue by ProDigySML** [bugcrowd/HUNT#34]
I think it would be nice to have the likely affected parameter identified by HUNT Scanner to be added to the search bar of the ITextEditor instance. This can be done using the `setSearchExpression` method of ITextEditor. 

I can make this change provided I can find the instance of each ITextEditor (shouldn't be that hard)

Do you think this would be worth a pull request? @swagnetow @jhaddix

**Comment by swagnetow** [comment]
So the way it's set up right now is that we're using the `IMessageEditorController` class which does not have access to `setSearchExpression`. The pros of using the `IMessageEditorController` class is that you get access to Burp's right click context menu and the request/response windows use Burp's native window which I think outweighs the usage of `setSearchExpression`.

I did make an issue on Burp's forums and apparently they're overhauling their API. So whenever that happens, we'll be sure to add the functionality.
