### ISSUE TITLE
Option to only add "in-scope" items (Nice to have feature)

### ISSUE THREAD

**Issue by ProDigySML** [bugcrowd/HUNT#35]
Yet another nice feature to have that would not be hard to implement. Can implement and add in a PR if you would like :) 

@swagnetow

**Comment by swagnetow** [comment]
Can you elaborate more on what you mean by this feature? Currently, you can limit in-scope items using a combination of the options in the Target and Scanner tabs.

**Comment by ProDigySML** [comment]
Yeah that was my bad. I thought the default of the drop down list was auto included in the filters. Sorry about that!
