### ISSUE TITLE
Readme contains misleading info

### ISSUE THREAD

**Issue by gerchicov-bp** [bugcrowd/HUNT#52]
`Step 3` sounds like "select some files with .py extension and add it to the app" with no concrete info.

Where to find these files? Are they different for different text fields? Should it be "hunt_scanner.py" file as on your screenshot? and etc.

**Comment by swagnetow** [comment]
This is fairly self-explanatory. You need to clone the git repo with the HUNT plugin code in it. That's what you're loading into Burp.
