### ISSUE TITLE
Question: Does HUNT scanner work with the community edition of Burp?

### ISSUE THREAD

**Issue by Curiosa04** [bugcrowd/HUNT#70]
As mentioned in the readme it could be installed in the community edition of Burp. HUNT scanner is however linked to the Burp scanner which isn't available in the community edition.

So, does the HUNT scanner works with the community edition?

Thanks in advance

**Comment by SimoneBovi** [comment]
Hi,
take a look at the README of the new version: https://github.com/bugcrowd/HUNT/blob/master/Remix/README.md

HUNT works with the Passive scanner, not the Active one. This is available also for the community edition.

Cheers,
Simone

**Comment by Curiosa04** [comment]
@SimoneBovi Thanks for pointing out the new repo. Remix extension is working fine! I see a ToDO for "Ability to add and modify rules". Does this mean that this repo isn't fully ported to the new repo (Is it gonna be fully ported to the new repo)?

**Comment by cak** [comment]
👋 @Curiosa04! The TODO means that in the future you will be able to add and modify the passive rules HUNT uses to identify potential vulnerable endpoints (instead of using the defaults).
